# FlexaBrain Core - Development Docker Compose
# Removed version attribute as it's deprecated in newer Docker Compose

services:
  # FlexaBrain Core Application
  flexabrain-core:
    build: .
    container_name: flexabrain-core
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://flexabrain:flexabrain_password@postgres:5432/flexabrain_dev
      - REDIS_URL=redis://redis:6379
      - OLLAMA_HOST=http://ollama:11434
      - NEXTAUTH_SECRET=your-secret-key-change-in-production
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - .:/app/src
    restart: unless-stopped
    networks:
      - flexabrain-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: flexabrain-postgres
    environment:
      POSTGRES_DB: flexabrain_dev
      POSTGRES_USER: flexabrain
      POSTGRES_PASSWORD: flexabrain_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flexabrain -d flexabrain_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - flexabrain-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: flexabrain-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - flexabrain-network

  # Ollama AI Model Server
  ollama:
    image: ollama/ollama:latest
    container_name: flexabrain-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    networks:
      - flexabrain-network
    # Add health check for Ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  ollama_models:
    driver: local

networks:
  flexabrain-network:
    driver: bridge